[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Prevent ESLint from failing the build on warnings
  ESLINT_IGNORE_WARNINGS = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment these lines to use a custom domain
# [[redirects]]
#   from = "https://example.com/*"
#   to = "https://www.example.com/:splat"
#   status = 301
#   force = true